name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
